//
// CLI extension functions.
//

// print() function.
success = 0
try {
	print('')
	success = 1
} catch {}
assert(success == 1)

// get_traceback() function.
success = 0
try {
	tb = get_traceback()
	success = 1
} catch {}
assert(success == 1)
assert(type(tb) == 'list')

// memory_get_usage() function.
success = 0
try {
	tb = memory_get_usage()
	success = 1
} catch {}
assert(success == 1)
assert(type(tb) == 'number')

// memory_get_peak_usage() function.
success = 0
try {
	tb = memory_get_peak_usage()
	success = 1
} catch {}
assert(success == 1)
assert(type(tb) == 'number')

// assert() function. This is used in examples/tests extensively and is expected
// to be a valid assertion. So let's try a failing assertion.
success = 0
try {
	assert(false)
} catch {
	// Failed assertion error is caught - this is a good thingâ„¢.
	success = 1
}
assert(success == 1)
